### ISSUE TITLE
Block-mode syntax discussion

### ISSUE THREAD

**Issue by Floffyko** [hfr/dokuwiki-plugin-asciidocjs#4]
I installed the plugin, Nodejs and all its extensions, but it work just one syntax to trigger the plugin: `//#--asciidoc--#//` , while syntax `<asciidoc>...</asciidoc>` has no effect, is not working. What could be the reason for this behavior? I really need the mixed mode of this nice plugin. An entire page, it is not something I always need.

**Comment by hfr** [comment]
I found the problem with the block-mode and I published a bugfix release.
I did not check if the update works.
So the save method is to remove the plugin and install it again.

The reason was my misunderstanding of the file structure.

**Comment by Floffyko** [comment]
Ok. I receive now the following error, twice:`Warning: file_get_contents(C:\xampp\htdocs\DkFL/lib/plugins/asciidocjs/asciidocinc.js): failed to open stream: No such file or directory in C:\xampp\htdocs\DkFL\lib\plugins\asciidocjs\syntax\base.php on line 131`. Could you please check where from the error is? Thanks

**Comment by hfr** [comment]
Sorry I was in the middle of a restructuring of the js code and forgot to include a new file in the repository.

**Comment by Floffyko** [comment]
Very nice. Second time I just updated from DW and it worked.  Now, Let's see why in block-mode the DW preview does not work, the content simple disapear. If We want to make complex nice mixed formatting, the preview is really useful. On another hand, whole / partial page syntax, `//#--asciidoc--#//`, preview work like a charm.

**Comment by hfr** [comment]
In my setup, the preview in block mode works without problems.

So I cannot fix this.

If you have node on the server, you can switch to a server side rendering.
By default the processing of the assciidoc to get html is done by the browser. Wikidoku embends the asciidoc content as json blocks in the html file and the browser converts it and place the html in the DOM of the browser.

You can switch to the server mode and then all the conversion is done at the server side. Only pure html is send to the browser.
